server:
  port: 9000  # 改成你想要的端口


logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
    level:
      root: INFO

spring:
  rabbitmq:
    host: 192.168.31.222 # 主机名
    port: 5672 # 端口
    virtual-host: /lin # 虚拟主机
    username: lin # 用户名
    password: 123 # 密码

#    publisher-confirm-type: correlated 	#开启 confirm 回调，correlated异步回调，simple同步
#    publisher-returns: true		#开启 return 回调（消息路由失败），路由失败一般是配置出错导致，一般不需要
#    template:
#      #定义消息路由失败时的策略。true，则调用ReturnCallback；false：则直接丢弃消息
#      mandatory: true


